### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gmer16** [OsiriX-Foundation/karnak#1]
Hi, a couple of brief questions.

Could you explain how would you publish the images to Kheops?
Suppose I can send images to _karnak_ using something like _storescu_, where can I configure the karnak input AET and PORT?
Regarding the de-identification of the images, where can you specify the anonymization rules?

Thanks

**Comment by nroduit** [comment]
This project is under development and is not yet ready for use. The de-identification part is not available yet.

Currently, it is possible to configure the gateway from the web interface to convert a DICOM input stream into a DICOMWeb output stream.

The configuration of the listener is defined [here](https://github.com/OsiriX-Foundation/karnak/blob/master/docker/run/karnak.env). In debug mode, you use Java VM options to change the default values.

**Comment by gmer16** [comment]
Ok, thank you very much.
