### ISSUE TITLE
Incorrect trailing (FFFE,E00D) Item Delimitation Item in outgoing C-STORE RQs.

### ISSUE THREAD

**Issue by gunterze** [OsiriX-Foundation/karnak#109]
Karnak appends _(FFFE,E00D) Item Delimitation Item_ to encoded  data sets in outgoing C-STORE RQs.

E.g.:
```
$ od --vx karnak-out-image-uncompressed.dcm | tail -n3
2002460 0016 0011 000a 0010 0012 000e 000b 000c
2002500 000c 0010 0011 fffe e00d 0000 0000
2002516
```
```
$ od -vx karnak-out-image-compressed.dcm | tail -n3
0033500 989f d9ff fffe e0dd 0000 0000 fffe e00d
0033520 0000 0000
0033524
```
```
$ od -vx karnak-out-sr.dcm | tail -n3
0005340 fffe e0dd 0000 0000 fffe e00d 0000 0000
0005360 fffe e0dd 0000 0000 fffe e00d 0000 0000
0005400
```

**Comment by nroduit** [comment]
Thank you for reporting this problem.
I had put this tag to try to solve another problem where sometimes the DICOM connections do not close (it hangs). It is now removed with this [commit](https://github.com/nroduit/weasis-dicom-tools/commit/ed5560c87b596f71909d910e82b43ca1b483338f#diff-b8f61c978f90ac617bfbeec5ead529a59a946102755f4362045d04e5440fb530L357).

I have opened a [issue](https://github.com/dcm4che/dcm4che20/issues/2) regarding the DICOM associations on dcm4che6.
