### ISSUE TITLE
Use of the DICOM structure according to Information Object Definition (IOD)

### ISSUE THREAD

**Issue by nicolasvandooren** [OsiriX-Foundation/karnak#11]
Using the DICOM innolitics data to check the type, VR, ...

Can be used in the DICOM profile standard, validation, ...

**Comment by nroduit** [comment]
Allows to know the path of the DICOM attributes and apply the right action for profile elements with multiple actions.

Allows to validate the right structure and the mandatory attributes according to a Sop Class.
