### ISSUE TITLE
Is there any way to compress the received instances before routering ?

### ISSUE THREAD

**Issue by luxunxiansheng** [OsiriX-Foundation/karnak#110]
It is a common task as we know.

**Comment by nroduit** [comment]
Technically it could be possible but it is not the role of the gateway to do this but rather of the system that receives the data. 
However the gateway decompresses on the fly when the transfer syntax (the type of compression) is not supported by the destination. This for the DICOM stream but not for the DICOMWeb.

**Comment by nroduit** [comment]
It has been implemented for the next release, see #139.
