### ISSUE TITLE
 jar： org.dcm4che6.img.* ，does not exist

### ISSUE THREAD

**Issue by bird-brother** [OsiriX-Foundation/karnak#113]
Import org.dcm4che6.img.*， does not exist in Profiles. java when compiling,and there is no such class in DCM4CHE20 source code。

DCM4CHE20:https://github.com/nroduit/dcm4che20.git

**Comment by nroduit** [comment]
Update the maven dependencies, it should come automatically from https://github.com/nroduit/mvn-repo/tree/master/org/dcm4che/dcm4che-img/6.0.0-SNAPSHOT

The repo is https://github.com/nroduit/dcm4che20/tree/image
