### ISSUE TITLE
Import an external pseudonym

### ISSUE THREAD

**Issue by nicolasvandooren** [OsiriX-Foundation/karnak#13]

**Comment by cicciu** [comment]
Implement a specific profile element 

1. If contain delimiter (if null take the entire value)
2. Position if contain delimiter
3. Tag

**Comment by nicolasvandooren** [comment]
Extract a pseudonym from an existing tag.
Need three value enter by the user.

Tag (Obligatory): The tag where the pseudonym is.
Delimiter (Obligatory if Position is present): The value used to split the value of the tag.
Position (Obligatory if Delimiter is present): The position in the array, after the split.

Example:
Tag: (0010,0010), Delimiter: ^ Position: 2
dcm.get(0010,0010) -> Test^for^pseudonym
Test^for^pseudonym.split(^) -> [Test, for, pseudonym]
[Test, for, pseudonym][2] -> pseudonym
