### ISSUE TITLE
Changing parameters during sending

### ISSUE THREAD

**Issue by nicolasvandooren** [OsiriX-Foundation/karnak#26]
Si on l'envoie des données et au milieu de l'envoie l'utilisateurs change de profiles, désactive/active la désidentification, ces changements seront appliqués instantanément aux restes des données.

Tester:
1. Envoyer des DICOMS à une destination non dés-identifié
2. En cours d'envoie, activer la dés-identification
3. Les données envoyées avant l'activation de la dés-identification, seront non dés-identifiées. Les données envoyées envoyées après la dés-identification, seront dés-identifiées.

**Comment by nroduit** [comment]
Duplicate of #31
