### ISSUE TITLE
Use DICOM endpoint as URL

### ISSUE THREAD

**Issue by nicolasvandooren** [OsiriX-Foundation/karnak#36]
The url defined in a destination STOW is not a DICOM endpoint, but Studies Service.

**Comment by nroduit** [comment]
Allow base DICOMWeb url or ending with studies. Examples of working URLs:
	http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs
	http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/  
	http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies
	http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies/
