### ISSUE TITLE
Check that the expression does not corrupt the DICOM

### ISSUE THREAD

**Issue by nicolasvandooren** [OsiriX-Foundation/karnak#74]
The following example will replace the patient's date of birth value with the value from the study description. This example shows that it is possible to attribute a Long String to a Date type.

expr: Replace(Tag.PatientBirthDate, getString(Tag.StudyDescription))

**Comment by nroduit** [comment]
Yes it should throw IllegalStateException that will abort the file transfer.

**Comment by nroduit** [comment]
Not valid for dcm4che3
